// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJYXTg21Uov6q4Se3liJ1RipT4YQaVwA',
    appId: '1:424125149466:web:f57941d4ec139b46e47ca3',
    messagingSenderId: '424125149466',
    projectId: 'handyman-4320f',
    authDomain: 'handyman-4320f.firebaseapp.com',
    storageBucket: 'handyman-4320f.appspot.com',
    measurementId: 'G-Q7MNWPZYSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm6HLT05pZ1kVTmWjwCZJbqSs3MYbfDCA',
    appId: '1:424125149466:android:a10e45ade1a760cee47ca3',
    messagingSenderId: '424125149466',
    projectId: 'handyman-4320f',
    storageBucket: 'handyman-4320f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXZ96RFZKzni_mLAq21ZSvc7ZRZDNK8q8',
    appId: '1:424125149466:ios:69fb24257c94ba97e47ca3',
    messagingSenderId: '424125149466',
    projectId: 'handyman-4320f',
    storageBucket: 'handyman-4320f.appspot.com',
    iosClientId: '424125149466-oa95hjkururiml0jon2e8ojuh531nr9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.handyman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXZ96RFZKzni_mLAq21ZSvc7ZRZDNK8q8',
    appId: '1:424125149466:ios:188693ebddee1c9fe47ca3',
    messagingSenderId: '424125149466',
    projectId: 'handyman-4320f',
    storageBucket: 'handyman-4320f.appspot.com',
    iosClientId: '424125149466-5ncvthf7lj936ts5bo528tuouauglvjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.handyman.RunnerTests',
  );
}
